definitions:
  pkg.Response:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /drivers/nearest:
    get:
      consumes:
      - application/json
      description: Get nearest driver
      parameters:
      - description: Latitude
        in: query
        name: lat
        required: true
        type: string
      - description: Longitude
        in: query
        name: long
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/pkg.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/pkg.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Get nearest driver
      tags:
      - drivers
swagger: "2.0"
